### ISSUE TITLE
Add more decimal fraction to ETH balance

### ISSUE THREAD

**Issue by decentralizedlove** [EverexIO/Ethplorer#10]
Add more decimal fraction to ETH balance

**Comment by ArtemKo7v** [comment]
ETH balance has percision of 18 decimals already, but we cut off trailing zeroes for better display. If you have an example of incorrect ETH balance rounding, it would be very helpful to post it here for further research. Thanks.

**Comment by leafcutterant** [comment]
I'm certain you don't have 18 decimals. My amount is missing 5 digits on your explorer and, to my surprise, it's rounded **up**.
