### ISSUE TITLE
Issue creating mongodb

### ISSUE THREAD

**Issue by jvilaikeo** [EverexIO/Ethplorer#11]
I tried installing the software to see if I could get ethplorer running but I'm running into a problem. I originally tried with php7 but the MongoClient class kept erroring because of php7 and moving to MongoDB/Clients. 

I'm trying to use as much of the defaults as possible but was not able to get past the dbName for the mongodb Construct. Error below. 

index.php
Changed $esCfg['mongo'] = TRUE ; // Changed from FALSE

Setup:

PHP 5.5.9
MongoDB 2.4
Mongo-php 1.4.5
Mongodb 1.2.9
Unbuntu 14.04

The Error:
PHP Fatal error:  Uncaught exception 'MongoException' with message 'MongoDB::__construct(): invalid name ' in /var/www/html/service/lib/ethplorer.php:94\nStack trace:\n#0 /var/www/html/service/lib/ethplorer.php(94): MongoClient->__get('')\n#1 /var/www/html/service/lib/ethplorer.php(118): Ethplorer->__construct(Array)\n#2 /var/www/html/index.php(23): Ethplorer::db(Array)\n#3 {main}\n  thrown in /var/www/html/service/lib/ethplorer.php on line 94

Line from ethplorer.php
                $oMongo = new MongoClient($this->aSettings['mongo']['server']);
                $oDB = $oMongo->{$this->aSettings['mongo']['dbName']};

Any ideas what I might be missing?

Thank you..

**Comment by jvilaikeo** [comment]
If I change $esCfg to TRUE, then I get the error:

PHP Notice:  Undefined index: client in /var/www/html/index.php on line 616

**Comment by alexesnsk** [comment]
It seems your PHP doesn't have mongo extension

**Comment by jvilaikeo** [comment]
This was pulled from my phpinfo() modules. Is this the proper extension?

mongo

MongoDB Support	enabled
Version	1.4.5
SSL Support	enabled
Streams Support	enabled

Directive	Local Value	Master Value
mongo.allow_empty_keys	0	0
mongo.chunk_size	262144	262144
mongo.cmd	$	$
mongo.default_host	localhost	localhost
mongo.default_port	27017	27017
mongo.is_master_interval	15	15
mongo.long_as_object	0	0
mongo.native_long	0	0
mongo.ping_interval	5	5

mongodb

MongoDB support	enabled
MongoDB extension version	1.2.9
MongoDB extension stability	stable
libbson bundled version	1.5.5
libmongoc bundled version	1.5.5
libmongoc SSL	enabled
libmongoc SSL library	OpenSSL
libmongoc crypto	enabled
libmongoc crypto library	libcrypto
libmongoc crypto system profile	disabled
libmongoc SASL	disabled

**Comment by beatcoinpl** [comment]
$oMongo = new MongoClient($this->aSettings['mongo']['server']);

This array gives me an error. In config i have changed:

`"mongo" => array(`

to 

`"mongodb" => array(`

**Comment by gochainwallet** [comment]
did you get this sorted
