### ISSUE TITLE
Documentation for getTokenInfo and getAddressInfo in Wiki is depreciated

### ISSUE THREAD

**Issue by chrisvensand** [EverexIO/Ethplorer#117]
The responses from getTokenInfo and getAddressInfo do not match the documentation.

example: 

API call, https://api.ethplorer.io/getAddressInfo/0xE90450a359C715C81a13aB12e1a9A68Ab6Ff5547?apiKey=freekey

Response:

{
    address: 
    name:
    decimals:
    symbol:
    totalSupply:
    owner:
    transfersCount:
    lastUpdated:
    issuancesCount:
    holdersCount:
    image:
    description:
    website:
    ethTrasfersCount:
    price:
    countOps:
}

Documentation:

{
    address:        # token address,
    totalSupply:    # total token supply,
    name:           # token name,
    symbol:         # token symbol,
    decimals:       # number of significant digits,
    price: {        # token price (false, if not available)
        rate:       # current rate
        currency:   # token price currency (USD)
        diff:       # 24 hour rate difference (in percent)
        ts:         # last rate update timestamp
    },
    owner:          # token owner address,
    countOps:       # total count of token operations
    totalIn:        # total amount of incoming tokens
    totalOut:       # total amount of outgoing tokens
    holdersCount:   # total numnber of token holders
    issuancesCount: # total count of token issuances
}

**Comment by lexa-m** [comment]
Thank you for the feedback.
Fixed.
