### ISSUE TITLE
Endpoint Not Found 

### ISSUE THREAD

**Issue by mchalise** [EverexIO/Ethplorer#120]
I tried every API endpoints from the wiki docs. But did not find endpoint to fetch 

> Transactional prices for all transfers

can someone help me with this. Thanks.

**Comment by mchalise** [comment]
![transaction_list_sample](https://user-images.githubusercontent.com/11830928/43721056-88a69646-99b1-11e8-8d7f-1e2551b9ee70.png)

**Comment by alexesnsk** [comment]
https://github.com/EverexIO/Ethplorer/wiki/ethplorer-api

`API's server address: http://api.ethplorer.io/, method GET.`

**Comment by alexesnsk** [comment]
> Transactional prices for all transfers
There is no such information in API.
