### ISSUE TITLE
Feature request: be able to get top holders of a specific token

### ISSUE THREAD

**Issue by samnet** [EverexIO/Ethplorer#122]
As can be seen here, most explorers display the top holders for any token, but none of them make this info available via API calls. 
https://www.reddit.com/r/ethereum/comments/8d8zzj/eth_blockchain_explorer_api_top_holders/

Being able to retrieve this info programmatically would be very valuable!

**Comment by Kryptoniq** [comment]
Hi @samnet,  is this what you are looking for? https://github.com/Kryptoniq/ERC20-Snapshot .

**Comment by alexesnsk** [comment]
Done: 
https://github.com/EverexIO/Ethplorer/wiki/Ethplorer-API#get-top-token-holders
