### ISSUE TITLE
service/lib/ethplorer.php is unable to load ../../vendor/autoload.php

### ISSUE THREAD

**Issue by xmaysonnave** [EverexIO/Ethplorer#123]
Hi All,
I try to install Ethplorer but I'm stuck as service/lib/ethplorer.php is unable to load ../../vendor/autoload.php
Is there anything to do to solve this issue as the repo doesn't seem any vendor directory ?
Thanks

**Comment by xmaysonnave** [comment]
I made a step further and figured out how to play with composer.
Now I'm stuck to install litipk/php-exceptions due to the following issue  :
https://github.com/Litipk/php-bignumbers/issues/63
Environment : docker, bionic, apache2, php7.2
Thanks

**Comment by ArtemKo7v** [comment]
The fix has been merged into develop branch.
Thank you.
