### ISSUE TITLE
Unable to get more than 10 (default) token operations using getTokenHistory

### ISSUE THREAD

**Issue by dhruvdcoder** [EverexIO/Ethplorer#124]
The following query should return last hundred operations.

[http://api.ethplorer.io/getTokenHistory/0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27?apiKey=freekey&limit=100&timestamp=1538559863](http://api.ethplorer.io/getTokenHistory/0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27?apiKey=freekey&limit=100&timestamp=1538559863)

However, it just sends last 10 operations.

**Comment by alexesnsk** [comment]
Check key limits:
https://github.com/EverexIO/Ethplorer/wiki/ethplorer-api#freekey-limits

free-key is limited for 10 operations per response.
