### ISSUE TITLE
Sent Token Still Displayed

### ISSUE THREAD

**Issue by slimz58** [EverexIO/Ethplorer#126]
A token I sent out of my eth wallet still shows when I scan my address on ethplorer. Any way to stop this from happening?

**Comment by SkAlauddin66** [comment]
Please saer password keysoter files deleted help you

**Comment by SkAlauddin66** [comment]
Please saer password keysoter files deleted help you

**Comment by slimz58** [comment]
> Please saer password keysoter files deleted help you

Please I dont understand. Can you explain more?
