### ISSUE TITLE
Paging issue, unable to move to the next page from getAddressTransactions

### ISSUE THREAD

**Issue by nisstal** [EverexIO/Ethplorer#129]
**Request**

http://api.ethplorer.io/getAddressTransactions/0xb297cacf0f91c86dd9d2fb47c6d12783121ab780?apiKey=freekey&limit=1&timestamp=1498717976

**Response**

{
    "error": {
        "code": 108,
        "message": "Invalid timestamp 2592000"
    }
}

**Comment by alexesnsk** [comment]
Check allowed timestamp range for your key.
