### ISSUE TITLE
/getTxInfo endpoint never return timestamp

### ISSUE THREAD

**Issue by jarenal** [EverexIO/Ethplorer#13]
Hi,

I'm using your API for get information of some transactions and I have an issue with the endpoint /getTxInfo

The timestamp always is null, I've tried with different transactions but no works.

An example:

https://api.ethplorer.io/getTxInfo/0xcebb6213bee1c406e50d010d16635ae38dd4e710f766c6cf16af57bb52a4747a?apiKey=freekey

Thanks in advance!

**Comment by ArtemKo7v** [comment]
@jarenal 
Fixed.  Thank you for reporting this issue.
