### ISSUE TITLE
Seems like timestamp limit not working

### ISSUE THREAD

**Issue by phplaboratory** [EverexIO/Ethplorer#132]
https://api.ethplorer.io/getTokenHistory/0xe94327d07fc17907b4db788e5adf2ed424addff6?apiKey=****&limit=2&timestamp=1549889315
https://api.ethplorer.io/getTokenHistory/0xe94327d07fc17907b4db788e5adf2ed424addff6?apiKey=****&limit=2&ts=1549889315

**Comment by ArtemKo7v** [comment]
Hello,

"timestamp" parameter specifies the **until** date.

In your case
https://api.ethplorer.io/getTokenHistory/address?apiKey=****&limit=2&timestamp=1549889315
you ask API to select 2 last records **before** timestamp 1549889315

**Comment by adteague** [comment]
I know this issue is closed, but this doesn't makes sense... every where else uses a timestamp to filter out anything that is before the timestamp, not after it 🤔  why would you do it this way???

**Comment by adteague** [comment]
so to get all transactions **after** a certain date I need to get all data (valid and invalid) to then loop through all the data and keep only the transactions after the date I want

seems like your server is going to be sending more data because of the inverse logic
