### ISSUE TITLE
Get All tokens name and address

### ISSUE THREAD

**Issue by Monarth-s** [EverexIO/Ethplorer#133]
Is there any API request available to get all ERC20 tokens name and addresses?

**Comment by juan21232** [comment]
Quiero mi pago

**Comment by Zovaxis** [comment]
!!!

**Comment by katya559** [comment]
0xe0c6CE3e73029F201e5C0Bedb97F67572A93711C

**Comment by nayeo89** [comment]
구 마이더월렛에서 뮤월렛으로 토큰 2종류가 옮겨지지 않았어요.
구버전에서   뮤 지갑으로 옮겨오려면 어떻게 해야되나요??
