### ISSUE TITLE
token id property not included in getAddressHistory endpoint results

### ISSUE THREAD

**Issue by consultantcraig** [EverexIO/Ethplorer#134]
In my portfolio tracking app, I import the latest transactions for all users' wallets, using the getAddressHistory  endpoint of the API.   For tokens that don't exist in my database, I generate them.   But I have the following problem:

1) token.symbol is not necessarily a unique identifier; token.id is
2) but token.id is not included on the token objects within the json results from getAddressHistory.

The end result is that in cases where there is a duplicate symbol, I have no way to resolve which token the object is referring to (except a combination of symbol and name, which is not ideal). 

Please add token.id to the results.   Thanks!

**Comment by ArtemKo7v** [comment]
Hello!

The only unique identity for a token is its **address**. 
So the right solution is to use token.address as token.id

**Comment by consultantcraig** [comment]
Ok, but as you may be aware neither coinmarketcap nor coinpaprika (whose apis can be used to get the latest market data on tokens) provide an address as a property of the token.  They each have their own id property.   I guess the fact that symbols for cryptocurrencies are not unique yet it's the only identifier currently used across the cryptosphere for looking up cryptos is troublesome.
