### ISSUE TITLE
getTokenHistory v2?

### ISSUE THREAD

**Issue by krijnsent** [EverexIO/Ethplorer#15]
Use case:
I'm trying to get all token transactions from one kind of token (say the BAT, contract 0x0D8775F648430679A709E98d2b0Cb6250d2887EF ), but have currently no option to loop through the transactions and get an overview of:
a) which accounts participated in the crowd sale/ICO (to make the chart of number of owners at the start of the coin)
b) to get an overview which accounts "dumped" their coins right after the ICO
c) to get a chart of the current owners of the coin

All those variations could make for nice plug-ins.

What I can imagine:
-getTokenHistoryGrouped: add 2 fields, "fromBlock" and "toBlock" (or fromTs and toTs)
-get those same parameters to work with getTokenHistory
-move some information from getTokenHistory to a header block. E.g. lastUpdated, holderscount, description . In that way the resulting JSON will be much smaller.

Unfortunately I have a hard time getting the code working with my local database, so hope you can put it on your todo list.

**Comment by gaia** [comment]
you can get C from here: https://ethplorer.io/address/0xe41d2489571d322189246dafa5ebde1f4699f498#tab=tab-transfers

but is there an API endpoint to get this information?
