### ISSUE TITLE
vendor/autoload.php  No such file

### ISSUE THREAD

**Issue by elastosDMA** [EverexIO/Ethplorer#161]
No such file or directory in F:\BaiduYunDownload\Ethplorer\service\lib\cache.php on line 18

**Comment by elastosDMA** [comment]
项目中文件缺失

**Comment by flwwsg** [comment]
需要安装php composer，然后运行composer install

**Comment by flwwsg** [comment]
> 项目中文件缺失
需要安装php composer，然后运行composer install
