### ISSUE TITLE
got reponse: {"code":108,"message":"Invalid timestamp 2592000"}}

### ISSUE THREAD

**Issue by leoaion** [EverexIO/Ethplorer#168]
request:
http://api.ethplorer.io/getAddressTransactions/0xe3124069e778572E494A3c9000e73B7d35C080e8?apiKey=freekey&limit=5&showZeroValues=true&timestamp=1561343225
response:
{"error":{"code":108,"message":"Invalid timestamp 2592000"}}

there is no 2592000 in request, how come does it return this error?

**Comment by lexa-m** [comment]
Hello,
"timestamp" parameter specifies the until date.
The most old date must be 30 days ago.
Your timestamp is specify to 24 Jun 2019.

Corrected error message to be more clear.
