### ISSUE TITLE
CSV Export down

### ISSUE THREAD

**Issue by zahin-mohammad** [EverexIO/Ethplorer#169]
Export as CSV link takes a user to `https://ethplorer.io/service/exportcsv.php?data=0x998497ffc64240d6a70c38e544521d09dcd23293&hash=e42b36cec9ae77be61190ad710dcb3e8&showTx=eth&showTx=eth&showTx=eth&showTx=eth`
Which shows the following :
![image](https://user-images.githubusercontent.com/24881706/68967046-3a20be00-0794-11ea-98ec-78a9da7233d7.png)

**Comment by alexesnsk** [comment]
Just click the export link from your browser. Do not try to save the link and reuse it again.
