### ISSUE TITLE
No matching DirectoryIndex (page568524.html) found, and server-generated directory index forbidden by Options directive

### ISSUE THREAD

**Issue by srivishnuk** [EverexIO/Ethplorer#18]
Hello,

after cloning the repo and changing php config file i get above error. I see this is configured as DirectoryIndex in htaccess also there is no file called page568524.html in source code nor other files mentioned in htaccess
RewriteRule ^last$ page627123.html
RewriteRule ^top$ page627210.html
RewriteRule ^about$ page627364.html
RewriteRule ^privacy$ page627373.html

Please direct me if its something wrong i am doing from my end

Regards,
Srivishnu.K

**Comment by edevil** [comment]
Yeah, I have the same problem.

**Comment by nbg15** [comment]
yes we have the same problem....

**Comment by GNUSource** [comment]
yes we have the same problem....

**Comment by guix77** [comment]
Same

**Comment by ArtemKo7v** [comment]
Static web pages of the site are not included in repository at the moment.
We will think how to solve this issue better.
Sorry for inconvenience.
