### ISSUE TITLE
Decimals not always string

### ISSUE THREAD

**Issue by ianaz** [EverexIO/Ethplorer#184]
Hi,
thanks for the job so far!
We're parsing your data via Golang and your json is mapped to structs. 

On the calls to `/getAddressInfo`, the attribute `tokens.tokenInfo.decimals` is pretty much always a string, except for some cases; for example here: http://api.ethplorer.io/getAddressInfo/0xb8012Acd96f92a57207B89573507be1961D48cDA?apiKey=freekey

Decentraland token's `decimals` is an integer, while as you can see others are always a string. Can this be consistent and either always be a string or always an int?

Thanks :)

**Comment by alexesnsk** [comment]
Duplicate https://github.com/EverexIO/Ethplorer/issues/172
