### ISSUE TITLE
API returns success to be empty word ("") with 900+ confirmations. The funds did actually arrive to the wallet

### ISSUE THREAD

**Issue by BadgerTheAdger** [EverexIO/Ethplorer#193]
Hi guys, [the request to API](https://api.ethplorer.io/getTxInfo/0x57ee644c5c15be703015b50c0c75f32dd56bd80bcfd4e71c80572a38f1e0ba40?apiKey=freekey) for the "0x57ee644c5c15be703015b50c0c75f32dd56bd80bcfd4e71c80572a38f1e0ba40" transaction returns success to be "" with 900+ confirmations. The funds did actually arrive to our wallet. Why would the API return empty word? Should we ignore the "success" thing and only rely on confirmations count?

**Comment by ArtemKo7v** [comment]
Fixed. Thank you!
