### ISSUE TITLE
Kovan API not working for getting topholders

### ISSUE THREAD

**Issue by true-eye** [EverexIO/Ethplorer#194]
https://kovan.etherscan.io/token/0xbf92F805B6114accf99eA0cf8F6056b93a3ac3ac#balances

0xbf92F805B6114accf99eA0cf8F6056b93a3ac3ac is a token address.
And I would like to get top token holders using ethplorer API.

https://kovan-api.ethplorer.io/getTopTokenHolders/0xbf92F805B6114accf99eA0cf8F6056b93a3ac3ac?apiKey=freekey&limit=10

But the response is
```
{
  "error": {
    "code": 150,
    "message": "Address is not a token contract"
  }
}
```

Could anyone help this?
Thanks in advance

**Comment by ArtemKo7v** [comment]
Fixed
Thank you

**Comment by true-eye** [comment]
Thank you for fixing the previous
But now it's also not working for other address

https://kovan-api.ethplorer.io/getTopTokenHolders/0x5D1D1684d85184cf170A73c98Dd9F4a0540a6DAA?apiKey=freekey&limit=44

As you can see, here is the token
https://kovan.etherscan.io/token/0x5D1D1684d85184cf170A73c98Dd9F4a0540a6DAA

Thanks, again

**Comment by true-eye** [comment]
I can't reopen this issue.
@ArtemKo7v 

Please let me know if you notified this. Thank you
