### ISSUE TITLE
Kovan api does not return getAddressTransactions value

### ISSUE THREAD

**Issue by BadgerTheAdger** [EverexIO/Ethplorer#195]
Hi everyone, I just made a [tx](https://kovan.ethplorer.io/tx/0xa28642e1a3ebd510288aff5047a6b1073a103d254fb0a026c683411a698c484e) to this address: **0xcD0a50d9bc7d639d47BaE0033F3423e1264084a7**. But it's not displayed in the api: https://kovan-api.ethplorer.io/getAddressTransactions/0xcD0a50d9bc7d639d47BaE0033F3423e1264084a7?apiKey=freekey

Could you take a look please and let me know if the issue is either on your side or mine?

**Comment by BadgerTheAdger** [comment]
I can see [another one](https://kovan-api.ethplorer.io/getAddressTransactions/0x8D781D5057D595d31771ed2Eaf22453e4Ed8e37B?apiKey=freekey) that I made a lot earlier today works has the data in the API... Is it a matter of time? But it's already been confirmed and it's already being displayed on your UI.

**Comment by BadgerTheAdger** [comment]
Also [api call to the transaction](http://kovan-api.ethplorer.io/getTxInfo/0xa28642e1a3ebd510288aff5047a6b1073a103d254fb0a026c683411a698c484e?apiKey=freekey) of this transaction gives me "confirmations":**-**10348062. Is it only for kovan? Take a look please

**Comment by ArtemKo7v** [comment]
Hello.

> Hi everyone, I just made a tx to this address: 0xcD0a50d9bc7d639d47BaE0033F3423e1264084a7. But it's not displayed in the api: https://kovan-api.ethplorer.io/getAddressTransactions/0xcD0a50d9bc7d639d47BaE0033F3423e1264084a7?apiKey=freekey
> 
> Could you take a look please and let me know if the issue is either on your side or mine?

```getAddressTransactions``` method can not be used to retrieve ERC20 operations. You need to use ```getAddressHistory``` method instead:
https://kovan-api.ethplorer.io/getAddressHistory/0xcD0a50d9bc7d639d47BaE0033F3423e1264084a7?apiKey=freekey


> Also api call to the transaction of this transaction gives me "confirmations": - (minus) 10348062. Is it only for kovan? Take a look please

There was an issue with the last block, fixed now!
Thank you!

**Comment by BadgerTheAdger** [comment]
0xb12b3ccefeb3fbfa6728f3c9d819608626df38735403f946392cee90774e786f this one (mainnet) gives me negative number of confirmations also... can you check?

**Comment by BadgerTheAdger** [comment]
@ArtemKo7v
