### ISSUE TITLE
Invalid Action while running on localhost

### ISSUE THREAD

**Issue by ahmer-yasin** [EverexIO/Ethplorer#20]
I have clone code and run in to my local machine setup mongodb is fine , but how to run ethereum in local machine, i have ubuntu 16.04.

I saw Invalid action and also it has some validations issue , 

Support Ethplorer.config is null so it will break the code not show the issue

**Comment by guix77** [comment]
Same

**Comment by PJijin** [comment]
Same here.

**Comment by madhat1** [comment]
Hi, how did you solve the mongodb problem?
Can you share how your'e running the server?
