### ISSUE TITLE
getAddressInfo may not return contractInfo

### ISSUE THREAD

**Issue by xavierlepretre** [EverexIO/Ethplorer#200]
This [contract](https://ethplorer.io/address/0x9992ec3cf6a55b00978cddf2b27bc6882d88d1ec) is a bit special as it was created by [this other contract](https://ethplorer.io/address/0x105b2b74fe6de95b68d435f3a3bc8ace03cf1658) inside [this transaction](https://ethplorer.io/tx/0x80942a699888c537f21722ad1a6c52c28fd1d2df5cf1f00c0a83aaee2bdccfb4).

Now, when I call the `/getAddressInfo/0x9992ec3cf6a55b00978cddf2b27bc6882d88d1ec` function, the result is missing the `contractInfo` elements. The other expected elements like `ETH` and `tokenInfo` are there and seem correct.

**Comment by ArtemKo7v** [comment]
We've fixed the issue for this address. 

However, the same problem still may occur with other similar contracts. 
We're working on the better handling internal transactions. 

Thank you.
