### ISSUE TITLE
getTopTokenHolders returns empty array

### ISSUE THREAD

**Issue by MrKyhme** [EverexIO/Ethplorer#203]
I have tried to use getTopTokenHolders, but it's not working properly - no matter which address I use, it returns an empty array. Even trying with an API-key :)

**Comment by alexesnsk** [comment]
> I have tried to use getTopTokenHolders, but it's not working properly - no matter which address I use, it returns an empty array. Even trying with an API-key :)

Just checked - it works. https://api.ethplorer.io/getTopTokenHolders/0xf3Db5Fa2C66B7aF3Eb0C0b782510816cbe4813b8?apiKey=freekey&limit=100

If the issue will repeat - please send an inquiry to the support contact form.
