### ISSUE TITLE
how to get the number of spent requests by free personal API key?

### ISSUE THREAD

**Issue by mrzlab630** [EverexIO/Ethplorer#205]
Hi guys. 
is there any way to get the number of spent requests by free personal API key from API Panel in the account?

**Comment by alexesnsk** [comment]
`Freekey` usage cannot be viewed in the panel because it is not linked to any user.  It is not intended for intensive use. Only for a small number of queries for easy development.
Use a personal key, it is free and has statistics in API Panel.

**Comment by mrzlab630** [comment]
> `Freekey` usage cannot be viewed in the panel because it is not linked to any user. It is not intended for intensive use. Only for a small number of queries for easy development.
> Use a personal key, it is free and has statistics in API Panel.

okay, great.
 but how can I get the number of spent requests by my personal key?
I don't want to go into the API Panel all the time
is there an API query for this?

**Comment by alexesnsk** [comment]
No API query, but you can calculate it on your side.

Normally you don't need that many queries unless you need to monitor new transactions for a lot of addresses.
[Bulk API Monitor](https://docs.ethplorer.io/monitor) is better for such a task.
