### ISSUE TITLE
is there any API query to get the number of spent requests by my personal key?

### ISSUE THREAD

**Issue by mrzlab630** [EverexIO/Ethplorer#206]
Hi guys.

how can I get the number of spent requests by my personal key?
I don't want to go into the API Panel all the time
is there any API query for this?

**Comment by alexesnsk** [comment]
Hi,

Normally you don't need that many queries unless you need to monitor new transactions for a lot of addresses.
[Bulk API Monitor](http://docs.ethplorer.io/monitor) is better for such a task. Check also [NodeJS client](https://github.com/amilabs/eth-bulk-monitor-client-nodejs) that makes usage easy with just a few lines of code.
