### ISSUE TITLE
BUG: Ethplorer API reports incorrect eth balance

### ISSUE THREAD

**Issue by kaiansaari** [EverexIO/Ethplorer#209]
Ethplorer API tracks balances incorrectly due to missing any eth transferred via internal transactions. This is a significant issue. See below:

https://api.ethplorer.io/getAddressInfo/0xc525daac6d307d219bd854bf50ff97016fa3c9a7?apiKey=yourapikey

`{"address":"0xc525daac6d307d219bd854bf50ff97016fa3c9a7","ETH":{"balance":0.001292595278115721,"price":{"rate":2374.7802085206013,"diff":-2.8,"diff7d":11.82,"ts":1618702382,"marketCapUsd":274313551174.00226,"availableSupply":115511132.4365,"volume24h":32150867531.48246,"diff30d":31.712218732515794,"volDiff1":-10.729856377487025,"volDiff7":9.296480171172178,"volDiff30":-0.174111066019762}},"countTxs":28}`

https://api.etherscan.io/api?module=account&action=balance&address=0xc525daac6d307d219bd854bf50ff97016fa3c9a7&tag=latest&apikey=YourApiKeyToken

`{"status":"1","message":"OK-Missing/Invalid API Key, rate limit of 1/5sec applied","result":"1292595278115721"}`

**Comment by kaiansaari** [comment]
Can confirm this is still an issue. Ethplorer eventually updates but for a long time (hours/days) it is incorrect

https://etherscan.io/address/0x58f3bf91d9cd535c20590bd034196767791e36ec
https://ethplorer.io/address/0x58f3bf91d9cd535c20590bd034196767791e36ec#

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/26814804/115960358-46e23d80-a554-11eb-9db1-f8817a0590f0.png">

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/26814804/115960363-52cdff80-a554-11eb-8d02-979a4358433b.png">

**Comment by bit-o-money** [comment]
> Can confirm this is still an issue. Ethplorer eventually updates but for a long time (hours/days) it is incorrect
> 
> https://etherscan.io/address/0x58f3bf91d9cd535c20590bd034196767791e36ec
> https://ethplorer.io/address/0x58f3bf91d9cd535c20590bd034196767791e36ec#
> 
> <img alt="image" width="1384" src="https://user-images.githubusercontent.com/26814804/115960358-46e23d80-a554-11eb-9db1-f8817a0590f0.png">
> 
> <img alt="image" width="1184" src="https://user-images.githubusercontent.com/26814804/115960363-52cdff80-a554-11eb-8d02-979a4358433b.png">

I have this issue currently. Ethplorer is not showing the balance of ETH after a BTC->ETH swap on AsgarDEX desktop 0.2.0 installed yesterday for the first time. Seed restore workaround in another wallet is not a solution thus far in any of the Native RUNE supporting wallets.

**Comment by alexesnsk** [comment]
The issue was immediately fixed in 2021. We apologize, missed the update here.
