### ISSUE TITLE
Is there an Ethplorer for BSC (Binance Smart Chain)?

### ISSUE THREAD

**Issue by chiwalfrm** [EverexIO/Ethplorer#212]
Not really an issue but I use this Ethplorer API extensively for Eth but now I am doing more on BSC (Binance Smart Chain) and I was wondering if you will be making this Ethplorer API for BSC?  Thank you

**Comment by zebtrijay** [comment]
is this available?

**Comment by egablefusion** [comment]
I would also like to see Ethplorer API on BSC and Polygon. I would be a paying customer on all three if you could provide it.

**Comment by alexesnsk** [comment]
Hello everybody!

The BSC explorer is available: https://binplorer.com
API endpoints and API-Keys are same as for ETH network, just use server: https://api.binplorer.com

Thanks!
