### ISSUE TITLE
Ethplorer doesn't show some token information while Etherscan does

### ISSUE THREAD

**Issue by 0xMars4204** [EverexIO/Ethplorer#221]
Please check these links below.

https://api.ethplorer.io/getAddressInfo/0xecdb3c18cb8f8a6c2d08c040e23927e5fb4c25e5?apiKey=

https://etherscan.io/address/0xecdb3c18cb8f8a6c2d08c040e23927e5fb4c25e5

Etherscan displays SNX token info, btw ethplorer doesn't.

Any help would be appreciated.

**Comment by ArtemKo7v** [comment]
Provided address does not have SNX token balance.
