### ISSUE TITLE
Difference between balance and transaction sum

### ISSUE THREAD

**Issue by EtWnn** [EverexIO/Ethplorer#224]
Hello there,

I sometimes notice a difference between the balance of a token and the sum of the transaction listed for an address.
Here is [an example for the FEG token](https://ethplorer.io/fr/address/0x2e8f3d197b91762e3535486748aeee51d347cdfa#showTx=tokens). (I picked an address with very few transaction for an easy example)

What I see in the transactions:  a total net transfert of 728 000 979 160 FEG
What I see in the balances: a total of 700,523,107,411.1158 FEG

Am I missing something or is there is issue with the site?
Thanks a lot!

**Comment by ArtemKo7v** [comment]
Hello

According to FEG token whitepaper, it has a 2% fee for every transaction. ~27,500,000.000 FEG tokens were additionally withdrawn as a tax fee with the last transfer, which nearly equals the difference between your calculated and actual balances.

**Comment by EtWnn** [comment]
Thanks a lot @ArtemKo7v , 
I should have searched better this particular token.
