### ISSUE TITLE
I can only pull 10 transactions using getAddressTransactions API

### ISSUE THREAD

**Issue by brianaliu** [EverexIO/Ethplorer#226]
Hi there,

I signed up for Personal key and tried to use Python to pull transactions from one wallet address. The code is as below. However, I can only get 10 transactions for 1 wallet address although I define 'limit' of 100. From the documentation, it says Max number of transactions/operations in response is 1000. Can someone please help me with this issue? Thanks!

payload_ethplorer1 = {
    'apiKey': myAPI,
    'limit': 100}
r_ethplorer1 = requests.get('https://api.ethplorer.io/getAddressTransactions/'+wallet_address, params=payload_ethplorer1)

**Comment by alexesnsk** [comment]
Just checked it up. The limit works well:
https://api.ethplorer.io/getAddressTransactions/0xb297cacf0f91c86dd9d2fb47c6d12783121ab780?apiKey=*****&limit=200

Returns 200 results.
