### ISSUE TITLE
Invalid API Key Widget not working

### ISSUE THREAD

**Issue by fiberson** [EverexIO/Ethplorer#229]
Hello. I used to use your widget to get information about smart contract transactions, but now, after 6 months it has become impossible. The widget just takes forever to load and gives an error in the console. Clicking on the error link it says 
"{"error":{"code":1, "message": "Invalid API key"}}".
After that I tried to generate API Key on Ethplorer API Panel, but it didn't work in the widget. The error is the same. And it is not clear what to do. I attach screenshots.

I hope for your help. Thank you!
![image](https://user-images.githubusercontent.com/54566317/158058699-67e1e3d6-3cfc-4f8b-99c4-f95ec9be8706.png)
![image](https://user-images.githubusercontent.com/54566317/158058717-272ff804-996a-4a4c-948a-2eec1ba84183.png)

**Comment by ArtemKo7v** [comment]
Hello.
We've fixed the issue.
Thank you for the signal.
