### ISSUE TITLE
Import Ethereum Blockchain Data into MongoDB

### ISSUE THREAD

**Issue by y-zono** [EverexIO/Ethplorer#23]
As far as I have seen the source code, there is no importing blockchain data into MongoDB feature. How can I import the data? To use this explorer, imported mongo data is necessary, isn't it?

If the importing tool does not exists yet, I want to know how to save the data from ethereum node.

I guess the following issue is same.

https://github.com/EverexIO/Ethplorer/issues/14

Ethplorer is a only open source explorer of Ethereum I could find. I want to use it.

**Comment by callmez** [comment]
same +1

**Comment by ekyang** [comment]
same +1

**Comment by drouillard** [comment]
@y-zono there is etherchain-light. I don't think it uses a database like Mongo though

**Comment by GamechainSystem** [comment]
same +1

**Comment by rmmaitrey** [comment]
@alexesnsk  Can you give some info about setting up DB with this script ?
I am bit new to this.

**Comment by xu10000** [comment]
Really disappointed to see that this is completely useless as the way to create the mongo database is not provided ...
