### ISSUE TITLE
API request issue in python\curl 

### ISSUE THREAD

**Issue by alexsith** [EverexIO/Ethplorer#231]
Hello. First of all, thank you very much for your service.
Second, since yesterday I am not able to request anything by using python 3.7 with request module 2.27.
If I open the same link in browser - it works. What kind of limitation you added?
log:

fetch Request: ethplorer GET http://api.ethplorer.io/getTop?apiKey=*******&criteria=cap&limit=50 RequestHeaders: {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: ethplorer GET http://api.ethplorer.io/getTop?apiKey=*******&criteria=cap&limit=50 404 ResponseHeaders: {'Date': 'Tue, 12 Apr 2022 08:37:22 GMT', 'Content-Type': 'text/html', 'Content-Length': '132', 'Connection': 'keep-alive', 'Etag': '"62541adf-84"'} ResponseBody: {"error":{"code":404,"message":"Invalid request, check API manual there: https://github.com/EverexIO/Ethplorer/wiki/Ethplorer-API"}}

**Comment by alexesnsk** [comment]
Use the https address. The end of http support was announced about a year ago.

**Comment by alexsith** [comment]
Thank you very much for your time. Issue fixed with me.
