### ISSUE TITLE
Can't see 'operations' in GetTxInfo response

### ISSUE THREAD

**Issue by carlius404** [EverexIO/Ethplorer#233]
Hi, I'm not able to get the 'operations' result from the GetTxInfo endpoint: /getTxInfo/{transaction hash}.
I've already done this, and I always got in the response the 'operations' key, but now it is not showing anymore.

TxHash='0xbfc5f400fc55de4a9532537bdde97b83574082b00153965ab8d21ec182cf4825'
url='https://api.ethplorer.io/getTxInfo/%s?apiKey=%s'%(TxHash,ApiKey)
res=requests.get(url)
res=json.loads(res.text)
print(res)
`{'hash': '0xbfc5f400fc55de4a9532537bdde97b83574082b00153965ab8d21ec182cf4825', 'timestamp': 1651760911, 'blockNumber': 14717765, 'confirmations': 50418, 'success': True, 'from': '0x3f35070ee0f2769cfd6e4b431cd02e6a10fc34e0', 'to': '0x7a250d5630b4cf539739df2c5dacb4c659f2488d', 'value': 0, 'input': '0x791ac94700000000000000000000000000000000000000000143f6ae743e4fc000000000000000000000000000000000000000000000000000000000006a94d74f43000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000003f35070ee0f2769cfd6e4b431cd02e6a10fc34e0000000000000000000000000000000000000000000000000000000006273e15f0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000ef3fc835bfae5f2063769a7c0d272060f765d3e3000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 'gasLimit': 2459721, 'gasUsed': 393196, 'logs': []}`

**Comment by alexesnsk** [comment]
Hi
Fixed for now. Please let us know if you will get this problem again.

**Comment by carlius404** [comment]
Ok thank you

Il ven 13 mag 2022, 18:18 alexesnsk ***@***.***> ha scritto:
