### ISSUE TITLE
getTokenHistory and getAddressTransactions are not returning correct transactions for tokens

### ISSUE THREAD

**Issue by Schiocco** [EverexIO/Ethplorer#236]
The method "getTokenHistory" is not returning correct transactions but other values.
For example, the correct transactions of the USDT address XXX from blockscout.com and etherscan.io are correct:

https://blockscout.com/eth/mainnet/api?module=account&action=tokentx&address=XXX&offset=10
https://api.etherscan.io/api?module=account&action=tokentx&address=XXX&startblock=0&endblock=99999999&sort=asc&apikey=12345678

The transactions returned by Ethplorer are different and wrong.

**Comment by alexesnsk** [comment]
Please provide the exact link and address to reproduce the problem. Specify what you think is wrong with the response.

It is impossible to reproduce the problem without exact examples.

**Comment by Schiocco** [comment]
I already explained in detail what the error is, I also provided exact examples (so no, it is not impossible but the inverse).
Anyway here some example links with my API keys (they should not be public):

https://api.etherscan.io/api?module=account&action=tokentx&address=0xD8C1ae8A9cE37Ee25aaa8Ed4399BB886dAbb903C&startblock=0&endblock=99999999&sort=asc&apikey=TBGQBHIXM113HT94ZWYY8MXGWFP9257541

https://blockscout.com/eth/mainnet/api?module=account&action=tokentx&address=0xD8C1ae8A9cE37Ee25aaa8Ed4399BB886dAbb903C&offset=10

Your explorer with bugs:

https://api.ethplorer.io/getAddressTransactions/0xD8C1ae8A9cE37Ee25aaa8Ed4399BB886dAbb903C?limit=150&showZeroValues=false&apiKey=EK-feNiM-th8gYm7-qECAq


And also, why did you close this issue if it is not close?
Thank you

**Comment by Schiocco** [comment]
Thanks for reopening

**Comment by ArtemKo7v** [comment]
To get all the token operations for the specific address you need to call getAddressHistory method.
https://api.ethplorer.io/getAddressHistory/0xD8C1ae8A9cE37Ee25aaa8Ed4399BB886dAbb903C?limit=150&showZeroValues=false&apiKey=freekey

**Comment by Schiocco** [comment]
Oh you are right! Thank you very much it was not mentioned in the docs.
