### ISSUE TITLE
Testnet 

### ISSUE THREAD

**Issue by moeadham** [EverexIO/Ethplorer#24]
Hi,

Do you have any data on testnet (ropsten, rikeby or other)?

**Comment by ArtemKo7v** [comment]
We do not have any public testnet instances at the moment.
But it is possible that we will make them public in future.

**Comment by flypaper0** [comment]
waiting for testnet support too

**Comment by allquantor** [comment]
Would be a great feature. +1 From me!

**Comment by hlogeon** [comment]
+1
Sometimes it's really important

**Comment by damonYuan** [comment]
+1

**Comment by nitika-goel** [comment]
+1

**Comment by ilejn** [comment]
+1

**Comment by kaysaith** [comment]
+1

**Comment by cipherzzz** [comment]
+1

**Comment by drwjf** [comment]
+1

**Comment by Lursun** [comment]
+1

**Comment by tkeidar** [comment]
+1

**Comment by bilguunb-UMS** [comment]
Any information on Test nets?
 (ROPSTEN or Rinkeby)? @ArtemKo7v

**Comment by alexesnsk** [comment]
https://kovan.ethplorer.io/
Also available in API and Bulk API

**Comment by mudrila** [comment]
Do you have any plans to have other networks, like rinkeby/ropsten/etc?
