### ISSUE TITLE
Delay retrieving getTxInfo

### ISSUE THREAD

**Issue by Unixcision** [EverexIO/Ethplorer#248]
Hi community,
I have developed a program that reads the transfers made from an address that also shows the information of the transfer. The etherscan API is instantaneous but does not offer advanced transaction data such as if it is a multiTransfer and it includes several transactions. The only API I've found that gives me such data is Ethplorer, but it's slow:
![image](https://user-images.githubusercontent.com/14082251/207025424-9fc1002c-0912-40a0-8969-abed45e37fa5.png)
As you can see, 2 minutes after the transaction was made it still appeared as 404, it took 3 minutes to finally display it.
Can it be faster? Is there any other way to get insant transaction info?
Thanks.

**Comment by alexesnsk** [comment]
Hi

This was a temporary delay. Some blockchain nodes were introducing delays. The seed is now normalized.
