### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by adamgering** [EverexIO/Ethplorer#33]
How do you page through getAddressHistory to get the next 10 records?
Tried page=N param, no luck.

**Comment by ArtemKo7v** [comment]
Pagination is not available in current API version, sorry.

**Comment by paulgerlich-wf** [comment]
Seriously? It's basically useless with only 10-50 results.

**Comment by alexesnsk** [comment]
https://github.com/EverexIO/Ethplorer/wiki/Ethplorer-API#get-last-address-operations

`timestamp: starting offset for operations [optional, unix timestamp]`
