### ISSUE TITLE
tokenInfo is not consistent when only one token vs multiple tokens in one address

### ISSUE THREAD

**Issue by Fuzzyma** [EverexIO/Ethplorer#35]
If one has only one token in their eth20 address, the json has one `tokenInfo` entry.
However when the address holds multiple tokens it now has an array `tokens` which holds multiple objects each having only a `tokenInfo` key. This is not consistent.

The normal and expected behavior should be:

- Having zero tokens:

```js
{
  // ... other info
 tokens: [] // empty array because no tokens
}
```

- Having one token:

```js
{
  // ... other info
 tokens: [ { information about the token } ] // one element in the array beeing a token object
}
```

- Having multiple tokens:

```js
{
  // ... other info
 tokens: [
    { information about the token } ,
    { information about the token } ,
    { information about the token } 
  ]
}
```

where `{ information about the token } ` is what is currently under `tokenInfo`.

This structure would benefit from more language features as well as beeing more consistent.

Would be cool, to have this in the next api version!

PS: Keep up the good work!

**Comment by ArtemKo7v** [comment]
You're correct and this is how it supposed to work.
We will investigate the issue.
Thank you for the remark!

**Comment by ArtemKo7v** [comment]
> However when the address holds multiple tokens it now has an array tokens which holds multiple objects each having only a tokenInfo key.

In addition to "tokenInfo", elements of "tokens" array also contain token balance.
So, the current response has this structure:

`{
  // ... other info
 tokens: [
    {balance: int, tokenInfo: { information about the token } } ,
    {balance: int, tokenInfo: { information about the token } } ,
    {balance: int, tokenInfo: { information about the token } }
  ]
}`

This is an important addition that makes the above consistent. In fact, "tokens" array should had to be named as "tokenBalances" or something like that. But, unfortunately, we cannot change API names due to backward compatibility.

**Comment by Fuzzyma** [comment]
No this does not make it consistent. Alone the fact that you sometimes get back an array and sometimes not is inconsistent. It always should be an array.
What you can change is "adding" something because that does not break the api.
Just always return a tokens array of the current form. Let everything else as it is. This way nothing gets broken and the overhead is minimal.

What do you think?

**Comment by ArtemKo7v** [comment]
Looks like the bug you're talking about is already fixed?

This address has only one token:

https://api.ethplorer.io/getAddressInfo/0x0082cb54cc466ef7dc512b1d836d9073bf0f68d2?apiKey=freekey

Result:
```
{
    "address":"0x0082cb54cc466ef7dc512b1d836d9073bf0f68d2",
    "ETH":{"balance":0.002844192,"totalIn":1.892844192,"totalOut":1.89},
     "countTxs":12,
     "tokens":[
         {"tokenInfo":   
{"address":"0x78b17cc10c4d34fbf6cb474731f7340e487a5db3","name":"Utemis","decimals":0,"symbol":"UTS","totalSupply":"0","owner":"0x0082cb54cc466ef7dc512b1d836d9073bf0f68d2","lastUpdated":1517210465840,"issuancesCount":0,"holdersCount":118,"price":false},
     "balance":999686449196,
     "totalIn":0,
     "totalOut":0}]
}
```
As you can see, "tokens" is an array having one element.

**Comment by Fuzzyma** [comment]
In that case I am sorry for not double checking! Thank you very much!
