### ISSUE TITLE
Get address info & show balances for specified token address only

### ISSUE THREAD

**Issue by DMPierre** [EverexIO/Ethplorer#38]
In `python 2.6`

Tried:

```
parameters = {'token': 'token_contract_address'}
re = requests.get('https://api.ethplorer.io/getAddressInfo/address?apiKey=freekey', params=parameters)
```

and 

`re = requests.get('https://api.ethplorer.io/getAddressInfo/address?apiKey=freekey&token=token_contract_address)` 

The second is basically the same. But tried in case of.

Both return:

`{u'error': {u'code': 104, u'message': u'Invalid address format'}}`

**Comment by DMPierre** [comment]
Turn around for `python 2.6`:

```
def getAddressTokeninfo(ethplorer_json, token_contract_address):
    """
    Parameters: 
    - ethplorer_json is the returned json data from ethplorer API for a specific address
    - token_contract_address is the token's address
    Returns:
    - A dictionary with data regarding the token
    """
    tokens, i = ethplorer_json['tokens'], 0
    while True:
        d = tokens[i]
        if d['tokenInfo']['address'] == unicode(token_contract_address.capitalize()):
            return d
            break
        else:
            continue
            i +=1

```

**Comment by alexesnsk** [comment]
https://github.com/EverexIO/Ethplorer/wiki/ethplorer-api#get-address-info

Correct format is: https://api.ethplorer.io/getAddressInfo/0xff71cb760666ab06aa73f34995b42dd4b85ea07b?apiKey=freekey

**Comment by markpeo** [comment]
What about the additional paramater - "token: show balances for specified token address.
How would that be added to the correct format?

**Comment by admkowal** [comment]
why this one is closed? In docs it clearly says about token param but it seems it is not supported?

**Comment by ArtemKo7v** [comment]
> why this one is closed? In docs it clearly says about token param but it seems it is not supported?

The `token` parameter seems to be working properly.

For example, in this request you will get only one token balance from an exchange address:
https://api.ethplorer.io/getAddressInfo/0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be?apiKey=freekey&token=0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9

And this request will return all the token balances of the same address.
https://api.ethplorer.io/getAddressInfo/0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be?apiKey=freekey

Please let us know if you have any issues using the `token` parameter.
