### ISSUE TITLE
API: How to get token info or value in USD from getAddressTransactions?

### ISSUE THREAD

**Issue by dzunghv** [EverexIO/Ethplorer#39]
Hi,

Example: https://api.ethplorer.io/getAddressTransactions/0x52903256dd18d85c2dc4a6c999907c9793ea61e3?apiKey=freekey
I can't know how to get token info or value in USD of each transaction, just have ETH value.

Please help me!
Thank you!

**Comment by QuangThong81** [comment]
Mau xanh luc

**Comment by alexesnsk** [comment]
usdPrice and usdValue are available in the response:
```
{
"timestamp": 1514982891,
"from": "0x6e41f3c09fbd3d8761791a5bf59efcc21c743c5d",
"to": "0x52903256dd18d85c2dc4a6c999907c9793ea61e3",
"hash": "0xe6eb35e89414de7213df7523389042db7c069c25ad32f1d0284afaa21b7de93c",
"value": 0.205,
"usdPrice": 939.737,
"usdValue": 192.64608499999997,
"success": true
},
```
