### ISSUE TITLE
wrong status on transaction.

### ISSUE THREAD

**Issue by ricardo85x** [EverexIO/Ethplorer#46]
Hi

The success status of this query is wrong. 

https://api.ethplorer.io/getTxInfo/0x28712f707b46def60efaa6f0f86575de76901ac276374891881fc063dec8db4a?apiKey=freekey

It says true, but it should say false

https://etherscan.io/tx/0x28712f707b46def60efaa6f0f86575de76901ac276374891881fc063dec8db4a

Thanks

**Comment by ArtemKo7v** [comment]
Thank you!
Fixed in 015253cd36589bbbb7926b9024807f29a805c5d1
