### ISSUE TITLE
Wrong account info when token smart contracts are updated. Augur (REP) example.

### ISSUE THREAD

**Issue by AoDev** [EverexIO/Ethplorer#51]
Ethplorer does not adapt to the smart contract updates.

For example, using the `getAddressInfo` API. Fetching the data of an address that has Augur (REP) token, will have this response:

See the "contract is frozen" line. `symbol`, `name` are missing, etc.

<img width="801" alt="screen shot 2018-03-01 at 10 26 10" src="https://user-images.githubusercontent.com/1526150/36836982-3b8ee41e-1d3b-11e8-96a8-e850a59c192e.png">

What is expected is the API to automatically use the new smart contract. Can we do something about it?

**Comment by ArtemKo7v** [comment]
No, when you ask for information about a specific address it is **absolutely** not expected to get details for another address. The fact that some company abandoned one contract and settled another one at another address with another code is important for the company, but not for the Blockchain.

I'd say it is not an Ethplorer failure, that Augur was unable to upgrade their contract without changing its address - technically could be possible.

**Comment by ArtemKo7v** [comment]
All the old REP contracts now have refs to the newer versions in the "alert" section.
