### ISSUE TITLE
get ETH info

### ISSUE THREAD

**Issue by skecskes** [EverexIO/Ethplorer#54]
Hi,

It says that ETH is not token when calling this:
https://api.ethplorer.io/getTokenInfo/0x0000000000000000000000000000000000000000?apiKey=freekey&price=ETH

but ETH is there when I am asking for topTen tokens:
https://api.ethplorer.io/getTop?apiKey=freekey

What is the best way to get info about ETH? Thank you

**Comment by adde11aid** [comment]
скорее всего твои токены в этом запросе отображаются в эфире

**Comment by pml10628** [comment]
RealBank(RBT) - 0xF75fC827A71Bf5b1273d35c90629dE4e173fb7aE

![coin-in system481](https://user-images.githubusercontent.com/24299277/52887928-adcf6500-3147-11e9-8a3d-a2ffd4d098f4.png)
