### ISSUE TITLE
How to get the ETH history

### ISSUE THREAD

**Issue by Sailor20** [EverexIO/Ethplorer#57]
I use the getAddressHistory or the getAddressTransactions, but it can't find the eth's history of one address to another, what should i do?

thanks for first

**Comment by alexesnsk** [comment]
ETH transactions is not available right now. It's in todo list.

**Comment by alexesnsk** [comment]
There is only history for one address is available.
https://github.com/EverexIO/Ethplorer/wiki/ethplorer-api#get-address-transactions

**Comment by adde11aid** [comment]
адрес истории не может быть связан с адресом транзакции
