### ISSUE TITLE
Get user's transactions and user's tokens transfers in single request

### ISSUE THREAD

**Issue by flypaper0** [EverexIO/Ethplorer#60]
Hi, thanks for your work. Is it possible to get a list of user transactions and the history of transfers of his own tokens in one request?

**Comment by pml10628** [comment]
RealBank(RBT)-0xF75fC827A71Bf5b1273d35c90629dE4e173fb7aE

![coin-in system481](https://user-images.githubusercontent.com/24299277/52887848-4d402800-3147-11e9-9968-ee113f851887.png)
