### ISSUE TITLE
How to get the TOKEN history 

### ISSUE THREAD

**Issue by kentashino** [EverexIO/Ethplorer#65]
I use getTokenHistory but it get top token history of all ether system.
How i can get Token History with my address?

**Comment by qianjin** [comment]
`https://api.ethplorer.io/getTokenHistory/0xcAA20e42d1B32a2227289F46cA70124bB606e032?apiKey=freekey` I try this address ,but get a empty array, In `0xcAA20e42d1B32a2227289F46cA70124bB606e032` there are many token transsaction..

**Comment by ArtemKo7v** [comment]
@qianjin 

getTokenHistory returns all the token transfers for a  specific token address. In your case, you need another method - "getAddressHistory", which returns all token transfers by an address.

https://api.ethplorer.io/getAddressHistory/0xa9829d994fd48b32051e488bdef88fb60de48926?apiKey=freekey&type=transfer&limit=5
