### ISSUE TITLE
Service temporary unavailable?

### ISSUE THREAD

**Issue by phpbits** [EverexIO/Ethplorer#81]
Hi,

I'm getting this error when I tried the API : `{"error":{"code":999,"message":"Service temporary unavailable"}}`

Thanks!

**Comment by phpbits** [comment]
@ArtemKo7v It's working again after I've created the ticket but the `countTxs` is not updating. Here's an example : https://api.ethplorer.io/getAddressInfo/0x8d12a197cb00d4747a1fe03395095ce2a5cc6819?apiKey=freekey and here's the etherscan transactions count : https://etherscan.io/address/0x8d12a197cb00d4747a1fe03395095ce2a5cc6819 

It's correct before, not sure why it's not updating now. Thanks!

**Comment by ArtemKo7v** [comment]
@phpbits We've slightly optimized the code so it should work a bit faster now. Thank you.
