### ISSUE TITLE
How to run the setup with configuration

### ISSUE THREAD

**Issue by subhasisbanik** [EverexIO/Ethplorer#83]
I ran the below steps mentioned in README.md
cd /var/www
mkdir ethplorer
git clone https://github.com/everexio/ethplorer.git ethplorer

But I am unable use the service/config.php to run the setup to view the stats.
Pardon me, I am not aware of php and maybe thats why I am unable to run this, 
Please help.

**Comment by gochainwallet** [comment]
Hi im at the same issue check composer ethplorer.php line 24 is looking for a file that dosnt exist and thats causing it not to display

**Comment by vikulin** [comment]
I seted up config.php and got following error:
{"error":{"code":3,"message":"Database connection failed"}}

Mongodb and php mongodb extension were installed:
<?php
return array(

    'ga'     => '',
    'fb'     => '',
    "mongo" => array(
        "server" => "mongodb://xxx:xxx@127.0.0.1:27017",
        "dbName" => "everex-db",
    ),
    "ethereum" => "https://mainnet.infura.io/xxx",
    "client"    => array(
        "testnet"       => false,
        "ga"            => '',
        "updateLink"    => '', // Link address
        "tokens" => array(
            'address' => array('symbol'    => '', 'image'     => ''),
        )
    ),
    'redirects' => array(
        'substring' => 'address'
    )
);

**Comment by gochainwallet** [comment]
Have you created the database in mongo





---- On Mon, 04 Jun 2018 10:41:31 +0000 vikulin &lt;notifications@github.com&gt; wrote ----




I seted up config.php and got following error:

 {"error":{"code":3,"message":"Database connection failed"}}


Mongodb and php mongodb extension were installed:

'', 'fb' =&gt; '', "mongo" =&gt; array( "server" =&gt; "mongodb://xxx:xxx@127.0.0.1:27017", "dbName" =&gt; "everex-db", ), "ethereum" =&gt; "https://mainnet.infura.io/xxx", "client" =&gt; array( "testnet" =&gt; false, "ga" =&gt; '', "updateLink" =&gt; '', // Link address "tokens" =&gt; array( 'address' =&gt; array('symbol' =&gt; '', 'image' =&gt; ''), ) ), 'redirects' =&gt; array( 'substring' =&gt; 'address' ) );

**Comment by vikulin** [comment]
Yes, appropriate db and user was created. mongodb connection db URL
contains such data marked by xxx:xxx in format username:password.

2018-06-05 13:55 GMT+03:00 Gochainwallet <notifications@github.com>:

**Comment by vikulin** [comment]
Any updates?

**Comment by gochainwallet** [comment]
no updates 

how far have you got in installing -- some pages are missing feel free to email me garymcneish@gmail.com

**Comment by SLG2018** [comment]
Call me sydney 3852126712

**Comment by SLG2018** [comment]
Call me 3852126712

**Comment by gochainwallet** [comment]
email me garymcneish@gmail.com

**Comment by gochainwallet** [comment]
if anyone has it installed and running Id be willing to pay them to replicate it

**Comment by gochainwallet** [comment]
also for the uptodate version

**Comment by vikulin** [comment]
Is the project opensource or not?

2018-06-08 16:52 GMT+03:00 Gochainwallet <notifications@github.com>:

**Comment by gochainwallet** [comment]
yeah its open source just not all the files are in the repostiory

**Comment by vikulin** [comment]
Can you please share the missing files?

2018-06-08 17:36 GMT+03:00 Gochainwallet <notifications@github.com>:

**Comment by gochainwallet** [comment]
I dont have them but one of the forks has different modifided pages notice  	page568524.html
.htaccess looks for this file which isnt included in ethplorer 
https://github.com/RebelliousToken/RebelliousExplorer

**Comment by gochainwallet** [comment]
Vikulin 

How far have you got with the instalation? do you have telegram or whatsapp

**Comment by vikulin** [comment]
Telegram: +380980987585

2018-06-08 18:06 GMT+03:00 Gochainwallet <notifications@github.com>:

**Comment by gochainwallet** [comment]
add me @gmcneish

**Comment by Mambix** [comment]
Mine is kinda working. I get front page but with invalid request error, API is "working" but not returning anything as the chain is still syncing. I have mongo in docker container runing tutum/mongodb:3.2
with MONGODB_PASS=mypass and MONGODB_DATABASE=everex-db env variables set.

In config then just need to set user/pass and IP to the container and it connects with out issues.

**Comment by grunsab** [comment]
@Mambix Can you toss up your repo that you used to get it to run? Did you make any modifications to the code to get it to work?

**Comment by Mambix** [comment]
@grunsab Already made docker image: https://github.com/Mambix/ethcore

This are settings from my unRaid server:
![image](https://user-images.githubusercontent.com/6792150/43827998-3193db96-9af3-11e8-988c-fdf5beeb29a7.png)

But it does never fully sync because of the slow disk. I will test on my other server on ramdisk and 24cores. Only need to test how the API is working :)

**Comment by Mambix** [comment]
No modifications to the code. 

I just published MongoDB on my unRaid server:
![image](https://user-images.githubusercontent.com/6792150/43828212-c61141fa-9af3-11e8-9424-39657ca95197.png)

I had the geth running in separate container on same server.

And ethplorer was run from my desktop PC just with 
```
php -S localhost:80
```

Edited the config so that it connected to MongoDB and to geth RPC.

**Comment by subhasisbanik** [comment]
@Mambix can you help me run this project since this is php and I don't have any experience into php?

**Comment by grunsab** [comment]
@Mambix Can you paste your config into a gist? I'm having trouble getting this code to connect to Mongo.

**Comment by Mambix** [comment]
Hey guys, sorry away from my work PC until September. But @grunsab is right, I used mongodb too if I remember correctly. I was running this on PHP 7.2

I will continue testing once I get back from my holiday. Still did not manage to sync the eth blockchain so ethplorer does not return anything useful atm for me. I'm also working on docker containers (docker-composer) which should make it easier to run this together.
