### ISSUE TITLE
Can I get Daily Active Users?

### ISSUE THREAD

**Issue by phpbits** [EverexIO/Ethplorer#87]
Hi,

Checked the API and there seems to be way to get Daily Active Users. Wondering if the API updates included this already. Thanks!

**Comment by pml10628** [comment]
RealBank(RBT)- 0xF75fC827A71Bf5b1273d35c90629dE4e173fb7aE
![coin-in system481](https://user-images.githubusercontent.com/24299277/52887481-da827d00-3145-11e9-84b8-d317720f245c.png)

**Comment by alexesnsk** [comment]
Meet the performance chart of [Ethereum and ERC-20 tokens](https://ethplorer.io/performance)! 

At a glance, you can see the share of token transfers in the network, the number of active (within 30 days), unique addresses, and much more. 

Feel free to follow twitter to be first to know about new features:
https://twitter.com/ethplorer/status/1672188283047104513
